### ISSUE TITLE
Well...

### ISSUE THREAD

**Issue by vypr** [MrDiamond123/Copyright-Law-That-Will-Let-Craftbukkit-Stay#1]
There was no rewrite. One of the contributors __added__ something that they rightfully owned (despite the fact its an open source license).

As noted in [this Bukkit forum post](https://bukkit.org/threads/bukkit-dmca-whats-going-on.309372/), Mojang can only keep Bukkit alive if:

1. Release the Minecraft server source code (as per Wolf's license) (Wolf is the guy who filed the DMCA complaint).
2. Or they rewrite Wolf's code.

Bukkit and CraftBukkit is gone now. Use Spigot or wait for Sponge to get stable.

Realistically, this seems like an immature attempt to get CraftBukkit back in action. The sources given don't back up your story any and there is no major explanation where this would work.

Rewriting isn't reproducing, rewriting something (granted you rewrite absolutely __everything__) would be perfectly eligible to be copyrighted. Reproducing is like redistributing (aka piracy).

To @Dinnerbone and @grum, sorry if the repo was any inconvenience.

**Comment by MrDiamond123** [comment]
What I am Saying is Bukkit And CraftBukkit is a Rewrite of The Minecraft Server Software.

**Comment by MrDiamond123** [comment]
I Hope I Solved It @vypr

**Comment by MrDiamond123** [comment]
Note: If Know Any Copyright Laws And Anything that can Save Bukkit And Craftbukkit I Will Add You And Let you edit it.
